---
- hosts: dbservers
  tasks:
    - name: Uptime
      bash: uptime
    - name: Hostname
      bash: hostname

- hosts: webservers
  tasks:
    - name: Uptime
      bash: uptime
    - name: List root
      bash: ls /

# - hosts: webservers
#   tasks:
#     - name: Server uptime
#       bash: uptime

#     - name: Server disk usage
#       bash: du -h