version: '3.8'
services:
  db1:
    build:
      context: .
      dockerfile: fakeserver.Dockerfile
    container_name: db1
    env_file:
      - .env
    environment:
      - USER=${USER}
      - PASSWORD=${PASSWORD}
    ports:
      - "2221:22"
  db2:
    build:
      context: .
      dockerfile: fakeserver.Dockerfile
    container_name: db2
    env_file:
      - .env
    environment:
      - USER=${USER}
      - PASSWORD=${PASSWORD}
    ports:
      - "2222:22"
  web1:
    build:
      context: .
      dockerfile: fakeserver.Dockerfile
    container_name: web1
    env_file:
      - .env
    environment:
      - USER=${USER}
      - PASSWORD=${PASSWORD}
    ports:
      - "2223:22"
  web2:
    build:
      context: .
      dockerfile: fakeserver.Dockerfile
    container_name: web2
    env_file:
      - .env
    environment:
      - USER=${USER}
      - PASSWORD=${PASSWORD}
    ports:
      - "2224:22" 

  orchestrator:
    build:
      context: .
      dockerfile: main.Dockerfile
    depends_on:
      - db1
      - db2
      - web1
      - web2
    volumes:
      - ./demo_files:/app/demo_files
    environment:
      - PYTHONUNBUFFERED=1
    stdin_open: true
    tty: true