---
- hosts: dbservers
  tasks:
  - name: Server uptime
    bash: uptime
  - name: Server disk usage
    bash: du -h

- hosts: webservers
  tasks:
  - name: Server uptime
    bash: uptime
  - name: Server disk usage
    bash: du -h