---
- hosts: dbservers
  tasks:
    - name: Uptime
      bash: uptime
    - name: Hostname
      bash: hostname
    - name: Disk usage
      bash: df -h
    - name: Kernel version
      bash: uname -a
    - name: List /var/lib (DB data?)
      bash: ls -lh /var/lib
    - name: Check for MySQL/Postgres
      bash: pgrep mysqld || pgrep postgres || echo "No DB process found"

- hosts: webservers
  tasks:
    - name: Uptime
      bash: uptime
    - name: Disk usage
      bash: df -h
    - name: Network interfaces
      bash: ip a || ifconfig
    - name: Open ports
      bash: netstat -tuln || ss -tuln
    - name: List /var/www (web root?)
      bash: ls -lh /var/www || echo "/var/www not found"
    - name: Check for nginx/apache
      bash: pgrep nginx || pgrep apache2 || echo "No web server process found"